config/routes.rb
Rails.application.routes.draw do

  root 'items#index'
  get 'items' => 'items#index'
  get 'items/new' => 'items#new'
  post 'items' => 'items#create'
  get 'items/:id' => 'items#show', as: :item
  get 'items/:id/edit' => 'items#edit', as: :edit_item
  patch 'items/:id' => 'items#update'

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to @item
    else
      render action: 'new'
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])

    if @item.update(item_params) 
      redirect_to @item
    else
      render action: 'edit'
    end
  end


  private

  def item_params
    params.require(:item).permit(:name, :price, :description, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<%= form_for @item do |f| %>
  
  Name: <%= f.text_field :name %><br>
  Description: <%= f.text_area :description, size: "30x3" %><br>
  Price: <%= f.number_field :price, step: 0.01 %><br>
  Image url: <%= f.text_field :image_url %><br>
  <%= f.submit %>

<% end %>

app/views/items/index.html.erb
<h1>List of Items</h1>
<ul>
<% @items.each do |item| %>

  <li><%= link_to item.name, item %></li>

<% end %>
</ul>

<%= link_to "Add Mo Fruit", items_new_path, class: "btn btn-success" %>

app/views/items/new.html.erb
<%= form_for @item do |f| %>
  
  Name: <%= f.text_field :name %><br>
  Description: <%= f.text_area :description, size: "30x3" %><br>
  Price: <%= f.number_field :price, step: 0.01 %><br>
  Image url: <%= f.text_field :image_url %><br>
  <%= f.submit %>

<% end %>

app/views/items/show.html.erb
<%= @item.name %><br>
$<%= @item.price %><br>
<%= @item.description %><br>
<%= image_tag @item.image_url %><br>

<%= link_to "Edit", edit_item_path, class: "btn btn-warning" %>
<%= link_to "Back", items_path, class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestfulRoutes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>